### ISSUE TITLE
Support for exporting 'custom' metrics

### ISSUE THREAD

**Issue by jim-mclean** [alphagov/paas-prometheus-exporter#33]
Pivotal's Cloud Foundry provides the ability to ingest custom metrics from deploy applications and emit them via Log Cache:  https://docs.pivotal.io/platform/application-service/2-7/metric-registrar/using.html

Could this project be updated to ingest these custom metrics and export them alongside the existing 'standard' metrics that are exported?

**Comment by tlwr** [comment]
Hi @jim-mclean, thanks for raising this

There is no reason why the exporter couldn't, at its core it just processes Loggregator envelopes and exposes them as an exporter to be scraped by Prometheus.

I assume you're mainly focused on the "Register a structured log" section rather than "Register a public metrics endpoint" section?

Would you be able to explain your use-case a bit more? i.e. how your Prometheus is set up in relation to your CF deployment, etc

**Comment by jim-mclean** [comment]
Actually I can see use using both approaches (logs/metrics endpoint) depending on the application.  If I understand the architecture in PCF correctly how the metrics get into Log Cache doesn't affect extracting that data.

Our Prometheus is deployed outside of PCF and currently pulls in metrics from a bunch of different infrastructure (Kafka, Cassandra).  We are looking for a way to get application metrics above and beyond the standard HTTP, CPU, Memory type metrics into a single system so that we  monitor and graph the health of our applications AND business processes.

**Comment by tlwr** [comment]
This project (presently), as you've established, is for taking application container metrics (memory, CPU, HTTPStartStop, etc) and some logs (crashes) from Loggregator and enabling them to be scraped.

I can see how using a structured log format to expose logs as metrics (we already do this for crashes), would be useful. Instead of setting your application instances up to be scraped (which brings concerns around authentication, routing, etc) they can emit events/metrics as logs which will get exposed as metrics, to be scraped by Prometheus.

I am still struggling to see how the public metrics endpoint would be useful in your case. As I understand it, the metrics-registrar, used with this exporter:
1. metrics-registrar scrapes your application instances for metrics
1. converts the metrics to loggregator envelopes
1. sends the envelopes through loggregator
1. the exporter then parses, computes, and exposes the metrics for scraping
1. Prometheus scrapes the exporter

In this case I think this loggregator-scrape-sandwich would introduce some unreliability and uncertainty about the timings of when metrics were gathered relative to when they were scraped.

I think for your use-case I would consider whether I wanted to have my applications be able to be scraped (pull), or to emit metrics (push into Loggregator, and expose).

If you want them to be scraped then you can use this project for application container metrics, and perhaps [Promregator](https://github.com/promregator/promregator) for custom application metrics. Your Prometheus would then scrape Promregator and the paas-prometheus-exporter separately.

If you want them to emit metrics as logs then this exporter, but modified might suit your needs.

Does that make sense?

Separately we're thinking about how to enable our users to expose custom application metrics, but it is currently lower down in our backlog, behind better backing service metrics.

**Comment by jim-mclean** [comment]
Thanks for the detailed reply!

My goal was to come up with a one-size-fits-all type approach.  Apps can get their metrics into 'the platfrom' and once there the can be exported (via this project) and/or used to for autoscaling decisions.

All that said, not sure where this question lands.  Are you planing on exposing custom metrics, or is that out of scope?

**Comment by tlwr** [comment]
I think it would be reasonable for this exporter to support the Gauge and Counter JSON log formats, out of the box.

In practical terms, the exporter would:

- continue to evaluate and expose non-log envelopes as well-defined metrics (cpu, memory)
- continue to parse and expose certain known log messages as well-defined metrics(crashes)
- parse and attempt to expose log messages in the formats described:

Counter:
```
{
  "type": "counter",
  "name": "some-counter",
  "delta": <>,
  "tags": {
    "tag1": "tag value"
  }
}
```

Gauge
```
{
  "type": "gauge",
  "name": "some-counter",
  "value": <>,
  "tags": {
    "tag1": "tag value"
  }
}
```

**Comment by jim-mclean** [comment]
Abandoning this idea in favor of using another tool (Promregator) to solve our 'custom' metrics problem.
